---
name: Main CI

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set Version
        id: set-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          [[ ${VERSION} =~ "refs/heads/" ]] && VERSION="${GITHUB_SHA::7}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-to: type=gha,scope=${{ github.workflow }}
          cache-from: type=gha,scope=${{ github.workflow }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}:${{ steps.set-version.outputs.version }}
